services:
  testedataseed:
    image: testedataseed
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn --host 0.0.0.0 --port 8000 dataseed.app:app"