"""Gerando tabela de transction

Revision ID: 749925d40a84
Revises: eb648413d73f
Create Date: 2025-08-01 11:12:50.433232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749925d40a84'
down_revision: Union[str, Sequence[str], None] = 'eb648413d73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('(0.00)'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('(0.00)'), nullable=False))
        batch_op.add_column(sa.Column('meal_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('(0.00)'), nullable=False))
        batch_op.add_column(sa.Column('cash', sa.Numeric(precision=10, scale=2), server_default=sa.text('(0.00)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cash')
        batch_op.drop_column('meal_amount')
        batch_op.drop_column('food_amount')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###
