"""Removendo campos obrigatórios da tabela de transction

Revision ID: da4cb355ca3a
Revises: 749925d40a84
Create Date: 2025-08-01 11:20:33.610579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4cb355ca3a'
down_revision: Union[str, Sequence[str], None] = '749925d40a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
